source 'https://cdn.cocoapods.org/'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
min_ios_version_supported = '12.4'
platform :ios, min_ios_version_supported
pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec', :modular_headers => true

target 'CodeChallenge' do
config = use_native_modules!
react_native_path = '../node_modules/react-native'

use_react_native!(
:path => react_native_path,
:hermes_enabled => true,
:flipper_configuration => FlipperConfiguration.disabled
)
target 'CodeChallengeTests' do
inherit! :complete
end

pre_install do |installer|
Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
installer.pod_targets.each do |pod|
    if pod.name.eql?('boost')
    def pod.build_type
        Pod::BuildType.static_library
    end
    end
end
end

post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
end
